"""Research agent - LLM planner-executor loop for agentic workflows.

The agent sees conversation history + tool schemas, plans tool calls, observes results,
and iterates. Supports budget controls, retry caps, and trace logging per hop.
"""

from __future__ import annotations

import json
import logging
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional

from src.modules.generation.model_router import RewriteModelRouter
from src.modules.orchestration.models import (
    CapabilityTag,
    Tool,
    ToolCall,
    ToolResult,
)
from src.modules.orchestration.tool_executor import ToolExecutor
from src.modules.orchestration.tool_registry import get_global_registry

logger = logging.getLogger(__name__)


@dataclass
class AgentStep:
    """Single step in the agent's reasoning trace."""

    step_number: int
    reasoning: str
    tool_calls: list[ToolCall] = field(default_factory=list)
    observations: list[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())


@dataclass
class AgentPlan:
    """Plan generated by the agent before execution."""

    tool_calls: list[ToolCall] = field(default_factory=list)
    estimated_cost_seconds: float = 0.0
    requires_approval: bool = False
    reasoning: str = ""
    tool_names: list[str] = field(default_factory=list)
    approved: bool = False
    plan_id: str = field(default_factory=lambda: f"plan_{int(time.time())}")
    out_of_scope: bool = False
    alternative_suggestion: str = ""


@dataclass
class AgentExecutionResult:
    """Result of agent execution."""

    success: bool
    final_answer: str
    steps: list[AgentStep]
    total_cost_seconds: float
    tool_results: dict[str, ToolResult] = field(default_factory=dict)
    error: Optional[str] = None


class ResearchAgent:
    """LLM planner-executor agent for research workflows."""

    def __init__(
        self,
        *,
        max_tool_calls: int = 10,
        max_retries: int = 3,
        user_id: Optional[str] = None,
        book_context: Optional[dict[str, Any]] = None,
    ) -> None:
        """Initialize the research agent.

        Args:
            max_tool_calls: Maximum number of tool calls per execution (budget control).
            max_retries: Maximum retry attempts for failed tool calls.
            user_id: Optional user ID for provenance.
            book_context: Optional dict with book_id, title, file_path, log_dir for current conversation.
        """
        self.max_tool_calls = max_tool_calls
        self.max_retries = max_retries
        self.user_id = user_id
        self.book_context = book_context or {}
        self.router = RewriteModelRouter()
        self.executor = ToolExecutor()
        self.registry = get_global_registry()

    def _build_planner_prompt(
        self,
        query: str,
        conversation_history: list[dict[str, str]],
    ) -> str:
        """Build the planner prompt with tool schemas and conversation context.

        Args:
            query: Current user query.
            conversation_history: Previous conversation turns.

        Returns:
            System prompt for the planner LLM.
        """
        book_id = self.book_context.get("book_id", "")
        book_title = self.book_context.get("title", "")
        file_path = self.book_context.get("file_path", "")
        log_dir = self.book_context.get("log_dir", "")

        tools = self.registry.list_all()

        # Build tool descriptions
        tool_descriptions = []
        for tool in tools:
            tags_str = ", ".join([t.value for t in tool.capability_tags])
            tool_descriptions.append(
                f"- {tool.name}: {tool.description}\n"
                f"  Tags: {tags_str}\n"
                f"  Input schema: {json.dumps(tool.input_schema.model_dump(exclude_none=True), indent=2)}"
            )

        tools_section = "\n\n".join(tool_descriptions)

        # Build conversation context
        context_parts = []
        for msg in conversation_history[-5:]:  # Last 5 turns
            role = msg.get("role", "user")
            content = msg.get("content", "")[:500]
            context_parts.append(f"{role}: {content}")

        conversation_context = "\n\n".join(context_parts) if context_parts else "No prior conversation."

        prompt = f"""You are a research planner for InsightEngine. You plan how to answer user queries using available tools.

Available tools:
{tools_section}

Your capabilities (what you CAN do):
- Read and search documents (list_documents, get_section, get_document_structure, search_documents)
- Traverse knowledge graphs for concept relationships (traverse_concepts)
- Rewrite sections with custom instructions (rewrite_section) - e.g., diagram-friendly, story-style, table-only
- Generate content from context (generate_content) - summaries, explanations, comparisons, tables
- Export to DOCX or Markdown (export_docx, export_markdown)
- Extract structured items with custom schemas (extract_items) - questions, definitions, dates, clauses, formulas
- Run full document pipelines (run_pipeline) - batch rewrite/generation jobs
- Build cross-book corpus indexes (build_corpus_index)

What you CANNOT do (these are out of scope):
- Generate videos, audio, or multimedia content
- Access external APIs or the internet
- Execute arbitrary code or system commands
- Modify the underlying document files directly
- Perform real-time web scraping
- Generate images or graphics beyond text-based diagrams
- Access user's local filesystem beyond the document corpus

Graceful degradation for out-of-scope requests:
- If asked for video generation → Offer: generate detailed script or storyboard using generate_content
- If asked for web scraping → Offer: search_documents for information if the content is already ingested
- If asked for image generation → Offer: generate detailed image descriptions or diagram text using rewrite_section
- If asked for external API access → Offer: work with already-ingested data or suggest manual data upload
- If asked for code execution → Offer: generate code snippets as text using generate_content
- If you cannot fulfill the request at all → Clearly explain the limitation and suggest the nearest alternative

Current document context:
- Book ID: {book_id}
- Book Title: {book_title}
- File path: {file_path}
- Log directory: {log_dir}

Use this book context for all tool calls that require book_id. If the user asks about chapters, sections, or content, assume they are referring to this current document.

Conversation context:
{conversation_context}

Current query: {query}

Return your plan as JSON with this structure:
{{
  "reasoning": "Your step-by-step reasoning",
  "tool_calls": [
    {{
      "tool_name": "tool_name",
      "input_data": {{...}},
      "reasoning": "Why this tool is needed"
    }}
  ],
  "estimated_steps": integer,
  "out_of_scope": boolean,
  "alternative_suggestion": string (if out_of_scope)
}}

Rules:
- Start with read/search tools before write tools
- Use search_documents for information retrieval
- Use traverse_concepts for knowledge graph exploration
- Use rewrite_section or generate_content for content creation
- Keep tool calls under {self.max_tool_calls} total
- If query is out of scope, set out_of_scope=true and provide alternative_suggestion
- Always offer a helpful alternative instead of just refusing
"""

        return prompt

    def _parse_planner_response(self, response: str) -> dict[str, Any]:
        """Parse the planner's JSON response.

        Args:
            response: Raw LLM response.

        Returns:
            Parsed plan dict.
        """
        try:
            # Try to extract JSON from response
            if "```json" in response:
                json_start = response.find("```json") + 7
                json_end = response.find("```", json_start)
                json_str = response[json_start:json_end].strip()
            elif "```" in response:
                json_start = response.find("```") + 3
                json_end = response.find("```", json_start)
                json_str = response[json_start:json_end].strip()
            else:
                json_str = response.strip()

            return json.loads(json_str)
        except json.JSONDecodeError:
            logger.warning("Failed to parse planner response, using fallback")
            return {
                "reasoning": response,
                "tool_calls": [],
                "estimated_steps": 0,
            }

    def plan(
        self,
        query: str,
        conversation_history: list[dict[str, str]],
    ) -> AgentPlan:
        """Generate a plan for answering the query.

        Args:
            query: User query.
            conversation_history: Conversation context.

        Returns:
            Agent plan with tool calls.
        """
        prompt = self._build_planner_prompt(query, conversation_history)

        result = self.router.generate(
            system_prompt="You are a research planner. Return valid JSON only.",
            user_prompt=prompt,
            max_tokens=1500,
        )

        plan_data = self._parse_planner_response(result.get("text", ""))

        # Check if query is out of scope
        if plan_data.get("out_of_scope", False):
            return AgentPlan(
                reasoning=plan_data.get("reasoning", ""),
                tool_calls=[],
                estimated_cost_seconds=0.0,
                requires_approval=False,
                tool_names=[],
                out_of_scope=True,
                alternative_suggestion=plan_data.get("alternative_suggestion", ""),
            )

        # Build tool call objects
        tool_calls = []
        total_cost = 0.0
        tool_names = []

        for tc_data in plan_data.get("tool_calls", []):
            tool_name = tc_data.get("tool_name")
            input_data = tc_data.get("input_data", {})

            tool = self.registry.get(tool_name)
            if not tool:
                logger.warning("Tool %s not found in registry, skipping", tool_name)
                continue

            tool_call = ToolCall(
                tool_name=tool_name,
                input_data=input_data,
                estimated_cost_seconds=tool.estimated_cost_seconds,
            )

            tool_calls.append(tool_call)
            total_cost += tool.estimated_cost_seconds
            tool_names.append(tool_name)

        # Check if plan requires approval (write or batch tools)
        requires_approval = any(
            self.registry.get(tc.tool_name).is_write
            if self.registry.get(tc.tool_name)
            else False
            for tc in tool_calls
        ) or any(
            self.registry.get(tc.tool_name).is_batch
            if self.registry.get(tc.tool_name)
            else False
            for tc in tool_calls
        )

        plan = AgentPlan(
            reasoning=plan_data.get("reasoning", ""),
            tool_calls=tool_calls,
            estimated_cost_seconds=total_cost,
            requires_approval=requires_approval,
            tool_names=tool_names,
        )

        logger.info(
            "Generated plan: %d tool calls, estimated cost %.1fs, requires_approval=%s",
            len(tool_calls),
            total_cost,
            requires_approval,
        )

        return plan

    def present_plan(self, plan: AgentPlan) -> dict[str, Any]:
        """Present a plan in a user-friendly format for approval.

        Args:
            plan: Agent plan to present.

        Returns:
            Dictionary with plan details for UI display.
        """
        tool_details = []
        for tc in plan.tool_calls:
            tool = self.registry.get(tc.tool_name)
            if tool:
                tool_details.append(
                    {
                        "tool_name": tc.tool_name,
                        "description": tool.description,
                        "is_write": tool.is_write,
                        "is_batch": tool.is_batch,
                        "estimated_cost_seconds": tool.estimated_cost_seconds,
                        "input_summary": str(tc.input_data)[:200],
                    }
                )

        return {
            "plan_id": plan.plan_id,
            "reasoning": plan.reasoning,
            "requires_approval": plan.requires_approval,
            "estimated_cost_seconds": plan.estimated_cost_seconds,
            "estimated_time_human": f"{plan.estimated_cost_seconds / 60:.1f} minutes",
            "tool_count": len(plan.tool_calls),
            "tools": tool_details,
            "tool_names": plan.tool_names,
        }

    def approve_plan(self, plan: AgentPlan, approved: bool) -> None:
        """Mark a plan as approved or rejected.

        Args:
            plan: Agent plan to approve/reject.
            approved: True to approve, False to reject.
        """
        plan.approved = approved
        logger.info("Plan %s %s", plan.plan_id, "approved" if approved else "rejected")

    def execute_plan(
        self,
        plan: AgentPlan,
        query: str,
        require_approval: bool = True,
    ) -> AgentExecutionResult:
        """Execute a plan and return the final answer.

        Args:
            plan: Agent plan to execute.
            query: Original user query.
            require_approval: If True, wait for approval before write/batch tools.

        Returns:
            Execution result with final answer and trace.
        """
        # Handle out-of-scope requests
        if plan.out_of_scope:
            return AgentExecutionResult(
                success=False,
                final_answer=f"I cannot fulfill this request directly. {plan.alternative_suggestion}",
                steps=[],
                total_cost_seconds=0.0,
                error="Request out of scope",
            )

        steps: list[AgentStep] = []
        tool_results: dict[str, ToolResult] = {}
        total_cost = 0.0

        # Check approval for write/batch tools
        if plan.requires_approval and require_approval:
            if not plan.approved:
                logger.info("Plan requires approval but not approved, returning early")
                return AgentExecutionResult(
                    success=False,
                    final_answer="Plan requires user approval. Please review and approve the plan before execution.",
                    steps=[],
                    total_cost_seconds=0.0,
                    error="Plan not approved",
                )
            logger.info("Plan approved, proceeding with execution")

        step_num = 1

        for tool_call in plan.tool_calls:
            if step_num > self.max_tool_calls:
                logger.warning("Max tool calls reached, stopping execution")
                break

            tool = self.registry.get(tool_call.tool_name)
            if not tool:
                steps.append(
                    AgentStep(
                        step_number=step_num,
                        reasoning=f"Tool {tool_call.tool_name} not found",
                    )
                )
                step_num += 1
                continue

            # Execute tool with retries
            result = None
            for attempt in range(self.max_retries + 1):
                result = self.executor.execute(
                    tool,
                    tool_call.input_data,
                    user_id=self.user_id,
                )

                if result.success or attempt == self.max_retries:
                    break

                logger.warning(
                    "Tool %s failed on attempt %d, retrying...",
                    tool_call.tool_name,
                    attempt + 1,
                )
                time.sleep(0.5)  # Brief delay before retry

            tool_results[tool_call.call_id] = result
            total_cost += result.execution_time_seconds

            # Record step
            observation = (
                f"Tool {tool_call.tool_name} succeeded"
                if result.success
                else f"Tool {tool_call.tool_name} failed: {result.error}"
            )

            step = AgentStep(
                step_number=step_num,
                reasoning=f"Execute {tool_call.tool_name}",
                tool_calls=[tool_call],
                observations=[observation],
            )

            steps.append(step)
            step_num += 1

        # Synthesize final answer from results
        final_answer = self._synthesize_answer(query, plan, steps, tool_results)

        return AgentExecutionResult(
            success=True,
            final_answer=final_answer,
            steps=steps,
            total_cost_seconds=total_cost,
            tool_results=tool_results,
        )

    def _synthesize_answer(
        self,
        query: str,
        plan: AgentPlan,
        steps: list[AgentStep],
        tool_results: dict[str, ToolResult],
    ) -> str:
        """Synthesize a final answer from tool results.

        Args:
            query: Original query.
            plan: Agent plan.
            steps: Execution steps.
            tool_results: Tool execution results.

        Returns:
            Final answer string.
        """
        # Build context from successful tool results
        context_parts = []

        for call_id, result in tool_results.items():
            if result.success:
                output = result.output
                if isinstance(output, dict):
                    context_parts.append(json.dumps(output, indent=2, default=str))
                else:
                    context_parts.append(str(output))

        context = "\n\n".join(context_parts) if context_parts else "No tool results available."

        prompt = f"""You are answering a user query based on tool execution results.

Query: {query}

Plan reasoning: {plan.reasoning}

Tool results:
{context}

Synthesize a clear, helpful answer that directly addresses the query.
Cite sources where relevant. Be concise but thorough.
If tools failed, acknowledge limitations.
"""

        result = self.router.generate(
            system_prompt="You are a helpful research assistant. Answer clearly and cite sources.",
            user_prompt=prompt,
            max_tokens=2000,
        )

        return result.get("text", "").strip()

    def run(
        self,
        query: str,
        conversation_history: list[dict[str, str]],
        require_approval: bool = True,
    ) -> AgentExecutionResult:
        """Run the full agent loop: plan → execute → synthesize.

        Args:
            query: User query.
            conversation_history: Conversation context.
            require_approval: Whether to require approval for write/batch tools.

        Returns:
            Execution result.
        """
        # Generate plan
        plan = self.plan(query, conversation_history)

        # Execute plan
        result = self.execute_plan(plan, query, require_approval=require_approval)

        return result
