"""Jobs API - durable job status and artifact listing for batch tools.

Provides endpoints for:
- Getting job status by job_id
- Listing jobs for a user
- Downloading job artifacts
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse

from auth.dependencies import get_current_user
from src.modules.orchestration.batch_tools import get_job_status
from storage.user_repository import UserRecord

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/jobs", tags=["jobs"])


@router.get("/{job_id}")
async def get_job_status_endpoint(
    job_id: str,
    current_user: UserRecord = Depends(get_current_user),
) -> dict:
    """Get the status of a batch job by job_id.

    Args:
        job_id: Job identifier.
        current_user: Authenticated user.

    Returns:
        Job status with progress, result, and error if any.
    """
    status = get_job_status(job_id)

    if status.get("status") == "not_found":
        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")

    return status


@router.get("/")
async def list_jobs(
    user_id: Optional[str] = Query(None, description="User ID to filter jobs (defaults to current user)"),
    status_filter: Optional[str] = Query(None, description="Filter by status: pending, running, done, error"),
    current_user: UserRecord = Depends(get_current_user),
) -> dict:
    """List jobs for a user with optional filtering.

    Args:
        user_id: User ID to filter (defaults to current user).
        status_filter: Optional status filter.
        current_user: Authenticated user.

    Returns:
        List of jobs with metadata.
    """
    from src.modules.orchestration.batch_tools import _job_store

    filter_user_id = user_id or current_user.user_id

    jobs = []
    for job_id, job_data in _job_store.items():
        # Filter by user if available
        if job_data.get("user_id") and job_data.get("user_id") != filter_user_id:
            continue

        # Filter by status if specified
        if status_filter and job_data.get("status") != status_filter:
            continue

        jobs.append(
            {
                "job_id": job_id,
                "status": job_data.get("status"),
                "progress": job_data.get("progress", 0),
                "message": job_data.get("message"),
                "created_at": job_data.get("created_at"),
                "result": job_data.get("result"),
                "error": job_data.get("error"),
            }
        )

    # Sort by created_at descending (newest first)
    jobs.sort(key=lambda j: j.get("created_at", 0), reverse=True)

    return {
        "jobs": jobs,
        "count": len(jobs),
        "user_id": filter_user_id,
    }


@router.get("/{job_id}/artifact")
async def download_job_artifact(
    job_id: str,
    current_user: UserRecord = Depends(get_current_user),
) -> FileResponse:
    """Download an artifact file generated by a job.

    Args:
        job_id: Job identifier.
        current_user: Authenticated user.

    Returns:
        File response with the artifact.
    """
    from src.modules.orchestration.batch_tools import _job_store

    job = _job_store.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")

    artifact_path = job.get("artifact_path")
    if not artifact_path:
        raise HTTPException(status_code=404, detail=f"Job {job_id} has no artifact")

    path = Path(artifact_path)
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Artifact file not found")

    return FileResponse(
        path=path,
        filename=path.name,
        media_type="application/octet-stream",
    )


@router.delete("/{job_id}")
async def delete_job(
    job_id: str,
    current_user: UserRecord = Depends(get_current_user),
) -> dict:
    """Delete a job record and its artifact.

    Args:
        job_id: Job identifier.
        current_user: Authenticated user.

    Returns:
        Confirmation message.
    """
    from src.modules.orchestration.batch_tools import _job_store

    job = _job_store.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")

    # Check ownership
    if job.get("user_id") and job.get("user_id") != current_user.user_id:
        raise HTTPException(status_code=403, detail="Not authorized to delete this job")

    # Delete artifact if exists
    artifact_path = job.get("artifact_path")
    if artifact_path:
        path = Path(artifact_path)
        if path.exists():
            path.unlink()

    # Remove from store
    del _job_store[job_id]

    return {
        "job_id": job_id,
        "deleted": True,
        "message": "Job deleted successfully",
    }
