# Common prompt templates for various LLM operations

# PROMPT for Chunk-by-Chunk Simplified Rewriting
PROMPT_EXTRACT_BOOK_STRUCTURE = (
    "You are an expert in analyzing book structures. Your task is to extract the hierarchical structure "
    "of the provided 'FULL BOOK TEXT'. This includes chapter titles, section headings, and subheadings, "
    "preserving their exact order and hierarchy. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **Output ONLY the JSON array.** DO NOT include any conversational text, markdown code block fences (```json), or any other characters before or after the JSON. "
    "2.  **DO NOT extract any explanations or content summaries.** ONLY extract the structure. "
    "3.  **DO NOT summarize content.** "
    "4.  **Output must be STRUCTURE ONLY.** "
    "5.  **Represent the structure as a JSON object with a 'structure' key containing an array of objects.** Each object should have a 'title' and an optional 'children' array for subheadings. "
    "6.  **Infer hierarchy based on formatting, numbering, and context.** "
    "7.  **Example Output Format (STRICTLY ADHERE TO THIS):**\n"
    "    ```json\n"
    "    {{\n"
    "        \"structure\": [\n"
    "            {{\n"
    "                \"title\": \"Chapter 1: Introduction to Thermodynamics\",\n"
    "                \"children\": [\n"
    "                    {{\"title\": \"First Law of Thermodynamics\"}},\n"
    "                    {{\"title\": \"Energy Transfer\"}},\n"
    "                    {{\n"
    "                        \"title\": \"Systems and Control Volumes\",\n"
    "                        \"children\": [\n"
    "                            {{\"title\": \"Closed Systems\"}},\n"
    "                            {{\"title\": \"Open Systems\"}}\n"
    "                        ]\n"
    "                    }}\n"
    "                ]\n"
    "            }},\n"
    "            {{\n"
    "                \"title\": \"Chapter 2: Properties of Pure Substances\",\n"
    "                \"children\": [\n"
    "                    {{\"title\": \"Phase-Change Processes\"}},\n"
    "                    {{\"title\": \"Property Tables\"}}\n"
    "                ]\n"
    "            }}\n"
    "        ]\n"
    "    }}\n"
    "    ```\n\n"
    "FULL BOOK TEXT:\n{full_text}\n"
)

PROMPT_MAP_CHUNK_TO_STRUCTURE = (
    "You are an expert in content organization and precise text extraction. Your task is to analyze the "
    "'CHUNK TEXT' and identify which of the provided 'BOOK STRUCTURE TITLES' it is relevant to. "
    "For each relevant title, you must extract *only* the sentences or paragraphs from the 'CHUNK TEXT' "
    "that directly explain or mention that specific topic. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **Output a JSON object with a 'mappings' key containing an array of objects.** Each object must have two keys: "
    "    *   `title`: The exact title of the structure node (string). "
    "    *   `source_text`: A string containing *only* the relevant sentences/paragraphs from the 'CHUNK TEXT' "
    "        that directly pertain to this `title`. If multiple parts of the chunk are relevant, merge them. "
    "2.  **Output ONLY the JSON object, enclosed within ````json` and ```` ` markdown fences.** DO NOT include any conversational text or any other characters before or after the JSON block. "
    "3.  **Match the `title` exactly as provided in 'BOOK STRUCTURE TITLES'.** "
    "4.  **Consider the full hierarchical path** (e.g., 'Chapter 1 > Section A > Subheading 1') when mapping. "
    "5.  **DO NOT rewrite, summarize, or generate explanations.** ONLY extract and attach raw PDF text. "
    "6.  **DO NOT add any new information.** The `source_text` must be verbatim from the 'CHUNK TEXT'. "
    "7.  **If a chunk contains content relevant to multiple nodes, create a separate object for each relevant node.** "
    "8.  **If a chunk does not clearly map to any specific node, return an empty array `[]` for the 'mappings' key.**\n"
    "9.  **Example Output Format (STRICTLY ADHERE TO THIS):**\n"
    "    ```json\n"
    "    {{\n"
    "        \"mappings\": [\n"
    "            {{\n"
    "                \"title\": \"Chapter 1: Introduction to Biology > Cell Structure\",\n"
    "                \"source_text\": \"The cell is the basic structural, functional, and biological unit of all known organisms.\"\n"
    "            }},\n"
    "            {{\n"
    "                \"title\": \"Chapter 1: Introduction to Biology > Cell Structure > Nucleus\",\n"
    "                \"source_text\": \"The nucleus is a membrane-bound organelle found in eukaryotic cells that contains most of the cell's genetic material.\"\n"
    "            }}\n"
    "        ]\n"
    "    }}\n"
    "    ```\n\n"
    "BOOK STRUCTURE TITLES:\n{book_structure_titles}\n\n"
    "CHUNK TEXT:\n{chunk_text}\n"
)

PROMPT_CONSOLIDATE_CONCEPTS = (
    "You are an expert in synthesizing information and removing redundancy. "
    "Your task is to consolidate the provided 'RAW NODE CONTENT' for a specific book structure node. "
    "Identify and combine repeated concepts or explanations within *this content only* into one coherent explanation. "
    "Preserve ALL unique information and remove all redundancy. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **DO NOT introduce any information not present in the RAW NODE CONTENT.** "
    "2.  **DO NOT remove any unique information.** "
    "3.  **DO NOT merge content ACROSS different structure nodes.** Focus strictly on the provided 'RAW NODE CONTENT'. "
    "4.  **Output the consolidated text in clear, simple English.** "
    "5.  **Maintain the original academic meaning.** "
    "6.  **Aggressively remove redundant words, phrases, or sentences.** Synthesize closely related sentences into one if they convey the exact same information. "
    "7.  **The output should be a single, coherent block of text** that represents all unique information from the raw content without repetition.\n\n"
    "RAW NODE CONTENT:\n{raw_node_content}\n"
)

PROMPT_REWRITE_NODE_CONTROLLED = (
    "You are an expert in simplifying complex academic texts for exam preparation, focusing on conceptual depth and clarity for a first-time reader. "
    "Your task is to rewrite the provided 'NODE CONTENT' for the topic '{node_title}' into detailed, clear, and exam-ready notes.\n"
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **SOURCE GUIDANCE & EXPANSION (MANDATORY):** Prioritize the provided 'NODE CONTENT'. If a point lacks sufficient detail to be self-explanatory or is too concise, you MUST expand on it by 15-20% and add relevant, concise examples to enhance clarity. These additions MUST be logical extensions of the existing content and NOT introduce new, unrelated concepts. Ensure the output is always more detailed than the input if the input is brief.\n"
    "2.  **DEPTH RULE (MANDATORY):** When rewriting, preserve ALL conceptual explanations, ALL examples, ALL illustrations, ALL exceptions and conditions, and ALL reasoning steps. You may simplify language, but NEVER simplify or remove ideas.\n"
    "3.  **CONCEPT USAGE vs. DEFINITION (CRITICAL):**\n"
    "    *   **Concept Definition Section:** If the 'NODE CONTENT' explicitly defines or elaborates on a concept (meaning, scope, elements, rationale, theory), provide a FULL explanation. Assume the reader is a complete beginner with no prior background in the subject.\n"
    "    *   **Concept Usage:** If a concept is merely used or referenced, DO NOT explain it here. Keep its usage brief and contextual.\n"
    "4.  **PRIMARY EXPLANATION vs. REFERENCE:** If this topic is the main place where a concept is explained, explain it in FULL. If another topic refers to it, only provide a brief contextual mention.\n"
    "5.  **DEDUPLICATION:** DO NOT repeat explanations. If a concept is listed in 'Concepts Already Explained', assume it has been covered and DO NOT explain it again. Only reference it if necessary.\n"
    "6.  **EXPLANATION STYLE (VERY IMPORTANT):** Rewrite content so a first-time reader can understand. Each concept should implicitly answer: What it is, Why it exists, How it applies, and What happens if violated or misused. Use short paragraphs, clear bullet points (`- `), numbered lists (`1. `), simple English, and a logical flow. Ensure consistent indentation for lists.\n"
    "7.  **EXAMPLES & ILLUSTRATIONS (DO NOT SHORTEN):** If examples or illustrations exist in the 'NODE CONTENT', keep ALL of them. Explain facts, context, and outcome in simple words. DO NOT compress them to one line or remove reasoning. Examples are learning tools, not just references.\n"
    "8.  **LENGTH CONTROL (IMPORTANT):** You MUST condense content by rewriting sentences in simpler English, breaking long sentences into clearer shorter sentences, or explaining existing ideas using different words already implied in the text. You MUST NOT add new concepts, examples, reasoning, or interpretations. Target output: 50-60% of original informational content, focusing on conciseness for a first-time learner. Ensure this reduction is always applied.\n"
    "9.  **ABSOLUTE PROHIBITIONS:**\n"
    "    *   ❌ No over-summarization.\n"
    "    *   ❌ No 'In short', 'Briefly', 'Simply put' replacements.\n"
    "    *   ❌ No conceptual shortcuts.\n"
    "    *   ❌ No skipping explanation because it was 'already mentioned' if this is the primary definition section.\n"
    "    *   ❌ DO NOT add generic introductions or conclusions. Start directly with the rewritten content.\n"
    "10. **Output Format (STRICTLY ENFORCED):** Provide only the rewritten text. DO NOT include any Markdown headings here; they will be added by the system. Ensure all lists (bulleted or numbered) are correctly formatted with a space after the marker (e.g., `- Item` or `1. Item`). **CRITICAL: For bullet points and numbered lists, ensure each item starts on a new line. Each bullet point or numbered list item MUST be on its own line. Ensure there is a blank line (`\\n\\n`) before the start of any list. If a bullet point or numbered list item is generated, it must be on its own line, and not immediately follow other text on the same line. Use a single newline (`\\n`) to separate paragraphs within a bullet point or list item, but ensure a blank line (`\\n\\n`) separates distinct bullet points or numbered list items from each other and from surrounding paragraphs. Also, ensure that if a bullet point or numbered list item contains multiple sentences, they are all part of the same list item and not broken into separate list items or paragraphs. Each distinct point in a list must be a separate bullet or numbered item. DO NOT allow any text to appear on the same line as a bullet point or numbered list marker, other than the content of that specific list item. If a list item contains sub-points, these should be indented and formatted as sub-lists.**\n"
    "11. **Concepts Already Explained (for reference, do not re-explain these):**\n{explained_concepts_context}\n\n"
    "NODE CONTENT:\n{node_content}\n"
)

PROMPT_CLASSIFY_INTENT = (
    "You are an Intent Processing Layer for an AI Knowledge Engine. "
    "Your task is to analyze the 'USER INPUT' and normalize it into a structured JSON intent object. "
    "DO NOT generate any content, answers, or summaries. ONLY output the JSON.\n\n"
    "**INTENT SCHEMA FIELDS:**\n"
    "- task_type: (rewrite_book, summarize_book, study_notes, revision_notes, question_answer)\n"
    "- scope: (full_book, specific_topic, single_question)\n"
    "- depth: (very_short, short, medium, detailed)\n"
    "- language_level: (simple, standard, advanced)\n"
    "- format_type: (paragraph, bullet, exam_oriented)\n"
    "- allow_external_knowledge: (true/false)\n"
    "- normalized_query: (A concise, search-optimized version of the user's request. Extract core topics, legal principles, or the main question to ensure high-quality knowledge retrieval.)\n\n"
    "**CRITICAL RULES:**\n"
    "1. Output ONLY the JSON object.\n"
    "2. Gemini is NOT allowed to generate content here. Only structured intent JSON.\n"
    "3. If the user asks a question, set task_type to 'question_answer', scope to 'single_question', and allow_external_knowledge to true.\n"
    "4. If the user wants a summary, set task_type to 'summarize_book'.\n"
    "5. If the user wants notes, set task_type to 'study_notes' or 'revision_notes'.\n"
    "6. Default language_level to 'standard' and depth to 'medium' unless specified.\n"
    "7. Ensure 'normalized_query' is ALWAYS present in the output JSON.\n\n"
    "USER INPUT: {user_input}\n"
)

PROMPT_REWRITE_CHUNK_SIMPLIFIED = (
    "You are an expert in simplifying complex academic texts for exam preparation. "
    "Your task is to rewrite the provided 'CHUNK TEXT' in *simpler, direct English*, making it *significantly shorter* (aim for 50% reduction), "
    "while strictly preserving the original meaning, structure, and order. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **DO NOT introduce any information that is not explicitly present in the CHUNK TEXT.** This includes explanations, background knowledge, interpretations, or reasoning not directly stated. "
    "2.  **DO NOT add examples unless they are explicitly present in the CHUNK TEXT.** If an example is in the text, simplify it. "
    "3.  **DO NOT combine information from different sections or chunks.** Process each chunk in isolation. "
    "4.  **DO NOT reorder topics or headings globally.** Maintain the original sequence of information as it appears in the CHUNK TEXT. "
    "5.  **DO NOT 'explain' concepts beyond simplifying their wording.** Focus on replacing complex sentences and difficult words with easier equivalents. "
    "6.  **DO NOT summarize across chunks.** Rewrite the content of *this specific chunk only*. "
    "7.  **Strict Heading Identification & Markdown Formatting (ABSOLUTE PRIORITY):** "
    "    *   **Identify headings and subheadings based on their visual cues in the original CHUNK TEXT** (e.g., bold text, distinct lines, numbering/lettering). "
    "    *   **Extract only the *semantic content* of the original heading.** Discard any original numbering or lettering (e.g., '1.1', 'A.', 'I.'). "
    "    *   **Apply the appropriate Markdown heading syntax (`#`, `##`, `###`)** based on the *inferred hierarchy* of the semantic content. "
    "        *   Use `#` (H1) for the main topic of the chunk. "
    "        *   Use `##` (H2) for major sub-sections. "
    "        *   Use `###` (H3) for minor sub-sections. "
    "    *   **CRITICAL: DO NOT create any NEW headings or subheadings that are not clearly present in the original CHUNK TEXT.** "
    "    *   **CRITICAL: All identified headings MUST be converted to Markdown headings for TOC generation.** "
    "    *   **DO NOT include any introductory text before the first identified heading of the chunk.** Start directly with the first Markdown-formatted heading. "
    "    *   **Use the provided 'OVERALL HEADINGS CONTEXT' to guide consistent heading levels across chunks.** If a heading appears as Level 1 in the overall context, it should be `#` in the output. If Level 2, `##`, etc. "
    "8.  **Aggressive Redundancy Reduction:** Identify and **AGRESSIVELY remove redundant words, phrases, or sentences** if the meaning remains unchanged. Synthesize closely related sentences into one, but only if they convey the exact same information. **DO NOT repeat information, even if slightly rephrased.** "
    "9.  **Clarify Unclear Sentences:** If a sentence is unclear in the original text, rewrite it clearly *WITHOUT adding any new meaning or making assumptions*. "
    "10. **Output Format:** The output should have the *same logical structure, same topics, and same order* as the input CHUNK TEXT, but with *shorter, clearer sentences*, *simpler vocabulary*, and **correct Markdown headings for TOC generation**. "
    "11. **No Prompt in Output:** DO NOT include any part of this prompt in your output. ONLY provide the rewritten chunk content.\n"
    "12. **No YAML or Horizontal Rules:** CRITICAL: DO NOT generate any YAML front matter (e.g., lines starting and ending with '---') or any content that could be misinterpreted as YAML metadata. **ABSOLUTELY AVOID using '---' or '***' or '___' as horizontal rule separators within the notes.**\n\n"
    "OVERALL HEADINGS CONTEXT:\n{overall_headings_context}\n\n"
    "CHUNK TEXT:\n{chunk}\n"
)

PROMPT_NORMALIZE_TOPIC = (
    "You are a precise topic normalization engine. Your task is to extract a 'canonical_topic_name' "
    "and a list of 'alternative_names' for the provided 'RAW TOPIC NAME' based on the 'CONSOLIDATED TEXT'.\n"
    "**CRITICAL RULES:**\n"
    "1. **NO CREATIVITY:** Use only terms found in or directly implied by the text.\n"
    "2. **NO EXPLANATIONS:** Do not explain the topic.\n"
    "3. **NO REWRITING:** Do not rewrite the content.\n"
    "4. **STRICT JSON:** Output ONLY a JSON object with the keys 'canonical_topic_name' (string) and 'alternative_names' (list of strings).\n"
    "5. **CANONICAL NAME:** The most formal, academic, or widely recognized name for the topic.\n"
    "6. **ALTERNATIVE NAMES:** Other ways the topic is referred to in the text (synonyms, acronyms, etc.).\n\n"
    "RAW TOPIC NAME: {raw_topic_name}\n"
    "CONSOLIDATED TEXT: {consolidated_text}\n"
)

PROMPT_DEDUPLICATE_TOPICS = (
    "You are a semantic deduplication engine. Your task is to identify topics that refer to the same "
    "underlying concept and group them together. For each group, you must decide on a 'primary' name "
    "and list the others as 'secondary' names.\n"
    "**CRITICAL RULES:**\n"
    "1. **SEMANTIC SIMILARITY:** Group topics based on meaning, not just string matching.\n"
    "2. **NO CONTENT REWRITING:** Do not change or summarize any content.\n"
    "3. **STRICT JSON:** Output ONLY a JSON object with a 'merge_groups' key containing a list of objects. "
    "Each object must have 'primary' (string) and 'secondary' (list of strings).\n"
    "4. **PRIMARY SELECTION:** Choose the most formal or comprehensive name as the primary name.\n"
    "5. **ONLY MERGE GROUPS:** Only include topics that actually need merging. If a topic is unique, do not include it in the output.\n\n"
    "TOPICS LIST:\n{topics_list}\n"
)

PROMPT_CLASSIFY_TOPIC = (
    "You are an exam-oriented topic classification engine. Your task is to analyze the provided "
    "'TOPIC NAME' and its 'CONSOLIDATED TEXT' to determine its importance and required explanation depth.\n"
    "**CRITICAL RULES:**\n"
    "1. **NO EXPLANATIONS:** Do not explain the topic.\n"
    "2. **NO REWRITING:** Do not rewrite the content.\n"
    "3. **EXAM LOGIC:** Prioritize core concepts, theories, and processes that are essential for exams.\n"
    "4. **STRICT JSON:** Output ONLY a JSON object with the following keys:\n"
    "   - 'topic_type': One of 'core_concept', 'sub_concept', 'definition_only', 'example', 'application', 'reference_only'.\n"
    "   - 'explanation_depth': One of 'detailed', 'brief', 'none'.\n"
    "   - 'definition_status': One of 'needs_explanation', 'already_explained', 'reference_only'.\n\n"
    "TOPIC NAME: {topic_name}\n"
    "FREQUENCY COUNT: {frequency_count}\n"
    "CONSOLIDATED TEXT: {consolidated_text}\n"
)

PROMPT_MAP_TOPIC_RELATIONSHIPS = (
    "You are a knowledge graph architect. Your task is to identify semantic relationships between a "
    "target 'TOPIC NAME' and a 'LIST OF OTHER TOPICS'.\n"
    "**CRITICAL RULES:**\n"
    "1. **NO REWRITING:** Do not change or summarize any content.\n"
    "2. **NO CIRCULARITY:** Ensure relationships are directional and logical.\n"
    "3. **STRICT JSON:** Output ONLY a JSON object with a 'relationships' key containing a list of objects.\n"
    "4. **RELATION TYPES:** Use ONLY the following relation types:\n"
    "   - 'depends_on': Target topic requires understanding of the other topic.\n"
    "   - 'explains': Target topic provides a definition or explanation for the other topic.\n"
    "   - 'applies': Target topic is a principle or theory applied in the context of the other topic.\n"
    "   - 'exception_to': Target topic is an exception to the rule or theory defined by the other topic.\n"
    "   - 'example_of': Target topic is a specific instance or illustration of the other topic.\n\n"
    "TOPIC NAME: {topic_name}\n"
    "LIST OF OTHER TOPICS: {list_of_other_topics}\n"
)

PROMPT_ACADEMIC_NOTE_WRITER = (
    "You are a professional academic note writer specializing in exam-oriented content. "
    "Your task is to write detailed, structured notes for the topic '{topic_name}' based on the provided 'NODE CONTENT'.\n"
    "**INPUT CONTEXT:**\n"
    "- **Explanation Depth:** {explanation_depth}\n"
    "- **Topic Relationships:** {topic_relationships}\n"
    "- **Already Explained Topics:** {already_explained_topics}\n\n"
    "**CRITICAL RULES:**\n"
    "1. **NO REPETITION:** If a concept is in 'Already Explained Topics', DO NOT explain it again. Instead, **cross-reference** it (e.g., 'See [Topic Name] for details').\n"
    "2. **EXPLANATION DEPTH:** Strictly follow the '{explanation_depth}' requirement. If 'none', only mention the topic. If 'brief', provide 2-3 lines. If 'detailed', provide a comprehensive explanation with examples, formulas, or processes as applicable.\n"
    "3. **FORMATTING:** Use clear **bullet points**. **Bold** key terms and academic principles.\n"
    "4. **TONE:** Maintain a formal, academic, and exam-oriented tone.\n"
    "5. **ILLUSTRATIONS:** If examples or illustrations are present in the content, preserve their core facts and outcomes, bolding the identifiers.\n"
    "6. **MARKDOWN ONLY:** Return the content in clean Markdown format. Do not include any introductory or concluding remarks.\n\n"
    "NODE CONTENT:\n{node_content}\n"
)
