# Common prompt templates for various LLM operations

# PROMPT for Chunk-by-Chunk Simplified Rewriting
PROMPT_EXTRACT_BOOK_STRUCTURE = (
    "You are an expert in analyzing book structures. Your task is to extract the hierarchical Table of Contents (TOC) "
    "of the provided 'FULL BOOK TEXT'. This structure will serve as a CLOSED SET of fixed structural slots.\n\n"
    "**HIERARCHY RULES:**\n"
    "Extract hierarchy in the following order: Chapter → Section → Topic.\n\n"
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **CLOSED SET:** Extract ONLY the structural slots present in the text. These will be the ONLY legal positions for content.\n"
    "2.  **HIERARCHY ONLY:** Extract titles and hierarchy ONLY. DO NOT extract explanations, summaries, or content.\n"
    "3.  **STRICT JSON:** Output ONLY the JSON object. No conversational text or markdown fences.\n"
    "4.  **Represent the structure as a JSON object with a 'structure' key containing an array of objects.** Each object should have a 'title' and an optional 'children' array for sub-nodes.\n"
    "5.  **Example Output Format:**\n"
    "    ```json\n"
    "    {{\n"
    "        \"structure\": [\n"
    "            {{\n"
    "                \"title\": \"Chapter 1: Introduction\",\n"
    "                \"children\": [\n"
    "                    {{\n"
    "                        \"title\": \"1.1 Background\",\n"
    "                        \"children\": [\n"
    "                            {{\"title\": \"1.1.1 Historical Context\"}}\n"
    "                        ]\n"
    "                    }}\n"
    "                ]\n"
    "            }}\n"
    "        ]\n"
    "    }}\n"
    "    ```\n\n"
    "FULL BOOK TEXT:\n{full_text}\n"
)

PROMPT_MAP_CHUNK_TO_STRUCTURE = (
    "You are an expert in content organization and precise text extraction. Your task is to analyze the "
    "'CHUNK TEXT' and identify which of the provided 'BOOK STRUCTURE TITLES' it is relevant to. "
    "For each relevant title, you must extract *only* the sentences or paragraphs from the 'CHUNK TEXT' "
    "that directly explain or mention that specific topic. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **Output a JSON object with a 'mappings' key containing an array of objects.** Each object must have two keys: "
    "    *   `title`: The exact title of the structure node (string). "
    "    *   `source_text`: A string containing *only* the relevant sentences/paragraphs from the 'CHUNK TEXT' "
    "        that directly pertain to this `title`. If multiple parts of the chunk are relevant, merge them. "
    "2.  **Output ONLY the JSON object, enclosed within ````json` and ```` ` markdown fences.** DO NOT include any conversational text or any other characters before or after the JSON block. "
    "3.  **Match the `title` exactly as provided in 'BOOK STRUCTURE TITLES'.** "
    "4.  **Consider the full hierarchical path** (e.g., 'Chapter 1 > Section A > Subheading 1') when mapping. "
    "5.  **DO NOT rewrite, summarize, or generate explanations.** ONLY extract and attach raw PDF text. "
    "6.  **DO NOT add any new information.** The `source_text` must be verbatim from the 'CHUNK TEXT'. "
    "7.  **If a chunk contains content relevant to multiple nodes, create a separate object for each relevant node.** "
    "8.  **If a chunk does not clearly map to any specific node, return an empty array `[]` for the 'mappings' key.**\n"
    "9.  **Example Output Format (STRICTLY ADHERE TO THIS):**\n"
    "    ```json\n"
    "    {{\n"
    "        \"mappings\": [\n"
    "            {{\n"
    "                \"title\": \"Chapter 1: Introduction to Biology > Cell Structure\",\n"
    "                \"source_text\": \"The cell is the basic structural, functional, and biological unit of all known organisms.\"\n"
    "            }},\n"
    "            {{\n"
    "                \"title\": \"Chapter 1: Introduction to Biology > Cell Structure > Nucleus\",\n"
    "                \"source_text\": \"The nucleus is a membrane-bound organelle found in eukaryotic cells that contains most of the cell's genetic material.\"\n"
    "            }}\n"
    "        ]\n"
    "    }}\n"
    "    ```\n\n"
    "BOOK STRUCTURE TITLES:\n{book_structure_titles}\n\n"
    "CHUNK TEXT:\n{chunk_text}\n"
)

PROMPT_CONSOLIDATE_CONCEPTS = (
    "You are an expert in synthesizing information and removing redundancy. "
    "Your task is to consolidate the provided 'RAW NODE CONTENT' for a specific book structure node. "
    "Identify and combine repeated concepts or explanations within *this content only* into one coherent explanation. "
    "Preserve ALL unique information and remove all redundancy. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **DO NOT introduce any information not present in the RAW NODE CONTENT.** "
    "2.  **DO NOT remove any unique information.** "
    "3.  **DO NOT merge content ACROSS different structure nodes.** Focus strictly on the provided 'RAW NODE CONTENT'. "
    "4.  **Output the consolidated text in clear, simple English.** "
    "5.  **Maintain the original academic meaning.** "
    "6.  **Aggressively remove redundant words, phrases, or sentences.** Synthesize closely related sentences into one if they convey the exact same information. "
    "7.  **The output should be a single, coherent block of text** that represents all unique information from the raw content without repetition.\n\n"
    "RAW NODE CONTENT:\n{raw_node_content}\n"
)

PROMPT_REWRITE_NODE_CONTROLLED = (
    "You are an expert in simplifying complex academic texts for exam preparation, focusing on conceptual depth and clarity for a first-time reader. "
    "Your task is to rewrite the provided 'NODE CONTENT' for the topic '{node_title}' into detailed, clear, and exam-ready notes.\n"
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **SOURCE GUIDANCE & EXPANSION (MANDATORY):** Prioritize the provided 'NODE CONTENT'. If a point lacks sufficient detail to be self-explanatory or is too concise, you MUST expand on it by 15-20% and add relevant, concise examples to enhance clarity. These additions MUST be logical extensions of the existing content and NOT introduce new, unrelated concepts. Ensure the output is always more detailed than the input if the input is brief.\n"
    "2.  **DEPTH RULE (MANDATORY):** When rewriting, preserve ALL conceptual explanations, ALL examples, ALL illustrations, ALL exceptions and conditions, and ALL reasoning steps. You may simplify language, but NEVER simplify or remove ideas.\n"
    "3.  **CONCEPT USAGE vs. DEFINITION (CRITICAL):**\n"
    "    *   **Concept Definition Section:** If the 'NODE CONTENT' explicitly defines or elaborates on a concept (meaning, scope, elements, rationale, theory), provide a FULL explanation. Assume the reader is a complete beginner with no prior background in the subject.\n"
    "    *   **Concept Usage:** If a concept is merely used or referenced, DO NOT explain it here. Keep its usage brief and contextual.\n"
    "4.  **PRIMARY EXPLANATION vs. REFERENCE:** If this topic is the main place where a concept is explained, explain it in FULL. If another topic refers to it, only provide a brief contextual mention.\n"
    "5.  **DEDUPLICATION:** DO NOT repeat explanations. If a concept is listed in 'Concepts Already Explained', assume it has been covered and DO NOT explain it again. Only reference it if necessary.\n"
    "6.  **EXPLANATION STYLE (VERY IMPORTANT):** Rewrite content so a first-time reader can understand. Each concept should implicitly answer: What it is, Why it exists, How it applies, and What happens if violated or misused. Use short paragraphs, clear bullet points (`- `), numbered lists (`1. `), simple English, and a logical flow. Ensure consistent indentation for lists.\n"
    "7.  **EXAMPLES & ILLUSTRATIONS (DO NOT SHORTEN):** If examples or illustrations exist in the 'NODE CONTENT', keep ALL of them. Explain facts, context, and outcome in simple words. DO NOT compress them to one line or remove reasoning. Examples are learning tools, not just references.\n"
    "8.  **LENGTH CONTROL (IMPORTANT):** You MUST condense content by rewriting sentences in simpler English, breaking long sentences into clearer shorter sentences, or explaining existing ideas using different words already implied in the text. You MUST NOT add new concepts, examples, reasoning, or interpretations. Target output: 50-60% of original informational content, focusing on conciseness for a first-time learner. Ensure this reduction is always applied.\n"
    "9.  **ABSOLUTE PROHIBITIONS:**\n"
    "    *   ❌ No over-summarization.\n"
    "    *   ❌ No 'In short', 'Briefly', 'Simply put' replacements.\n"
    "    *   ❌ No conceptual shortcuts.\n"
    "    *   ❌ No skipping explanation because it was 'already mentioned' if this is the primary definition section.\n"
    "    *   ❌ DO NOT add generic introductions or conclusions. Start directly with the rewritten content.\n"
    "10. **Output Format (STRICTLY ENFORCED):** Provide only the rewritten text. DO NOT include any Markdown headings here; they will be added by the system. Ensure all lists (bulleted or numbered) are correctly formatted with a space after the marker (e.g., `- Item` or `1. Item`). **CRITICAL: For bullet points and numbered lists, ensure each item starts on a new line. Each bullet point or numbered list item MUST be on its own line. Ensure there is a blank line (`\\n\\n`) before the start of any list. If a bullet point or numbered list item is generated, it must be on its own line, and not immediately follow other text on the same line. Use a single newline (`\\n`) to separate paragraphs within a bullet point or list item, but ensure a blank line (`\\n\\n`) separates distinct bullet points or numbered list items from each other and from surrounding paragraphs. Also, ensure that if a bullet point or numbered list item contains multiple sentences, they are all part of the same list item and not broken into separate list items or paragraphs. Each distinct point in a list must be a separate bullet or numbered item. DO NOT allow any text to appear on the same line as a bullet point or numbered list marker, other than the content of that specific list item. If a list item contains sub-points, these should be indented and formatted as sub-lists.**\n"
    "11. **Concepts Already Explained (for reference, do not re-explain these):**\n{explained_concepts_context}\n\n"
    "NODE CONTENT:\n{node_content}\n"
)

PROMPT_CLEAN_AND_SEMANTIC_CHUNK = (
    "You are an expert in document processing and semantic analysis. Your task is to take the provided 'RAW TEXT' from a PDF and transform it into a series of clean, idea-based semantic chunks.\n\n"
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1. **NOISE REMOVAL:** Aggressively remove all non-content elements, including:\n"
    "   - Headers and footers\n"
    "   - Page numbers\n"
    "   - Copyright notices and publisher information\n"
    "   - Repetitive book/chapter titles at the top/bottom of pages\n"
    "   - Artifacts from PDF extraction (e.g., stray characters, broken lines)\n"
    "2. **SEMANTIC CHUNKING:** Instead of fixed-size chunks, split the text based on *complete ideas or concepts*. A chunk should contain one main idea and its immediate supporting details.\n"
    "3. **NO CHAPTER INFERENCE:** Do NOT try to group chunks into chapters or sections yet. Just output the individual semantic chunks.\n"
    "4. **PRESERVE MEANING:** Do NOT summarize or rewrite the content. Keep the original wording as much as possible, but ensure it is clean and coherent.\n"
    "5. **OUTPUT FORMAT:** Output a JSON object with a 'chunks' key containing an array of strings. Each string is one semantic chunk.\n"
    "6. **STRICT JSON:** Output ONLY the JSON object. No conversational text or markdown fences.\n\n"
    "RAW TEXT:\n{raw_text}\n"
)

PROMPT_DISCOVER_CONCEPTS = (
    "You are an expert Concept Discovery Agent. Your task is to analyze the provided 'SEMANTIC CHUNK' and extract ONLY the most significant academic or technical terms.\n\n"
    "**SELECTIVITY RULES (CRITICAL):**\n"
    "Be highly selective. Do NOT extract every noun. Only extract terms that are central to the academic subject matter.\n\n"
    "**CLASSIFICATION RULES (MANDATORY):**\n"
    "Classify EACH term found as one of the following:\n"
    "1. **EXPLAINED_CONCEPT**: The term is explicitly defined or explained in detail. It must be the primary focus of a significant portion of the text.\n"
    "2. **REFERENCED_ONLY**: The term is mentioned but not explained. Only include if it is a major technical term.\n"
    "3. **DEPENDENCY_ONLY**: The term is a prerequisite for understanding other concepts.\n\n"
    "**STRICT CONCEPT CREATION RULES:**\n"
    "ONLY terms classified as **EXPLAINED_CONCEPT** are candidates for becoming full topics. For these, you MUST provide 'verbatim_evidence'.\n\n"
    "**FORBIDDEN:**\n"
    "Do NOT extract:\n"
    "- Common words or general vocabulary.\n"
    "- Passing references to people, places, or dates unless they are core concepts.\n"
    "- Redundant terms that refer to the same idea.\n\n"
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1. **BOTTOM-UP EXTRACTION:** Extract directly from the text.\n"
    "2. **NO HIERARCHY:** Output a flat list of terms only.\n"
    "3. **OUTPUT FORMAT:** Output a JSON object with a 'terms' key containing an array of objects. Each object must follow this schema:\n"
    "   - term: The primary name of the term.\n"
    "   - classification: (string) 'EXPLAINED_CONCEPT', 'REFERENCED_ONLY', or 'DEPENDENCY_ONLY'.\n"
    "   - verbatim_evidence: (string or null) Quoted verbatim text from the chunk providing the explicit explanation (Required for EXPLAINED_CONCEPT).\n"
    "   - source_location: (string) Approximate location within the chunk.\n"
    "   - confidence: A float between 0.0 and 1.0.\n"
    "4. **STRICT JSON:** Output ONLY the JSON object.\n\n"
    "SEMANTIC CHUNK:\n{semantic_chunk}\n"
)

PROMPT_BUILD_BLUEPRINT = (
    "You are an expert Knowledge Architect. Your task is to take a list of 'DISCOVERED CONCEPTS' and organize them into a canonical, hierarchical 'KNOWLEDGE BLUEPRINT'.\n\n"
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1. **SEMANTIC DEDUPLICATION:** Identify concepts that are semantically identical and merge them into a single canonical concept.\n"
    "2. **HIERARCHY BUILDING:** Establish relationships between concepts based on:\n"
    "   - **Dependency:** Concept A must be understood before Concept B.\n"
    "   - **Containment:** Concept B is a sub-component or specific type of Concept A.\n"
    "3. **CHAPTER INFERENCE:** Group related concepts into logical 'Chapters' based on their semantic clusters and dependencies. This must happen AFTER concepts are identified.\n"
    "4. **IMMUTABILITY:** The resulting blueprint must be a complete, self-contained representation of the book's knowledge. It will be used as an immutable reference for all future operations. NEVER delete or shorten examples at this stage.\n"
    "5. **OUTPUT FORMAT:** Output a JSON object with the following structure:\n"
    "   - chapters: An array of objects, each with 'title' and 'sections' (list of objects).\n"
    "       - Each section has 'title' and 'concept_ids' (list of strings).\n"
    "   - concepts: An array of objects, each following the Concept Discovery schema (including tagged examples), but with added 'dependencies' (list of concept_ids).\n"
    "   - global_confidence: A float representing the overall quality of the blueprint.\n"
    "6. **STRICT JSON:** Output ONLY the JSON object. No conversational text or markdown fences.\n\n"
    "DISCOVERED CONCEPTS:\n{discovered_concepts}\n"
)

PROMPT_CLASSIFY_INTENT = (
    "You are an Intent Processing Layer for an AI Knowledge Engine. "
    "Your task is to analyze the 'USER INPUT' and normalize it into a structured JSON intent object. "
    "DO NOT generate any content, answers, or summaries. ONLY output the JSON.\n\n"
    "**INTENT SCHEMA FIELDS:**\n"
    "- task_type: (rewrite_book, summarize_book, study_notes, revision_notes, question_answer)\n"
    "- scope: (full_book, specific_topic, single_question)\n"
    "- depth: (very_short, short, medium, detailed)\n"
    "- language_level: (simple, standard, advanced)\n"
    "- format_type: (paragraph, bullet, exam_oriented)\n"
    "- allow_external_knowledge: (true/false)\n"
    "- refers_to_original_structure: (true/false) Set to true if the user explicitly refers to the original book structure (e.g., 'Chapter 4', 'Section 2.1', 'Topic 3.2.1').\n"
    "- normalized_query: (A concise, search-optimized version of the user's request. Extract core topics, legal principles, or the main question to ensure high-quality knowledge retrieval.)\n\n"
    "**CRITICAL RULES:**\n"
    "1. Output ONLY the JSON object.\n"
    "2. Gemini is NOT allowed to generate content here. Only structured intent JSON.\n"
    "3. If the user asks a question, set task_type to 'question_answer', scope to 'single_question', and allow_external_knowledge to true.\n"
    "4. If the user wants a summary, set task_type to 'summarize_book'.\n"
    "5. If the user wants notes, set task_type to 'study_notes' or 'revision_notes'.\n"
    "6. Default language_level to 'standard' and depth to 'medium' unless specified.\n"
    "7. Ensure 'normalized_query' is ALWAYS present in the output JSON.\n\n"
    "USER INPUT: {user_input}\n"
)

PROMPT_REWRITE_CHUNK_SIMPLIFIED = (
    "You are an expert in simplifying complex academic texts for exam preparation. "
    "Your task is to rewrite the provided 'CHUNK TEXT' in *simpler, direct English*, making it *significantly shorter* (aim for 50% reduction), "
    "while strictly preserving the original meaning, structure, and order. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **DO NOT introduce any information that is not explicitly present in the CHUNK TEXT.** This includes explanations, background knowledge, interpretations, or reasoning not directly stated. "
    "2.  **DO NOT add examples unless they are explicitly present in the CHUNK TEXT.** If an example is in the text, simplify it. "
    "3.  **DO NOT combine information from different sections or chunks.** Process each chunk in isolation. "
    "4.  **DO NOT reorder topics or headings globally.** Maintain the original sequence of information as it appears in the CHUNK TEXT. "
    "5.  **DO NOT 'explain' concepts beyond simplifying their wording.** Focus on replacing complex sentences and difficult words with easier equivalents. "
    "6.  **DO NOT summarize across chunks.** Rewrite the content of *this specific chunk only*. "
    "7.  **Strict Heading Identification & Markdown Formatting (ABSOLUTE PRIORITY):** "
    "    *   **Identify headings and subheadings based on their visual cues in the original CHUNK TEXT** (e.g., bold text, distinct lines, numbering/lettering). "
    "    *   **Extract only the *semantic content* of the original heading.** Discard any original numbering or lettering (e.g., '1.1', 'A.', 'I.'). "
    "    *   **Apply the appropriate Markdown heading syntax (`#`, `##`, `###`)** based on the *inferred hierarchy* of the semantic content. "
    "        *   Use `#` (H1) for the main topic of the chunk. "
    "        *   Use `##` (H2) for major sub-sections. "
    "        *   Use `###` (H3) for minor sub-sections. "
    "    *   **CRITICAL: DO NOT create any NEW headings or subheadings that are not clearly present in the original CHUNK TEXT.** "
    "    *   **CRITICAL: All identified headings MUST be converted to Markdown headings for TOC generation.** "
    "    *   **DO NOT include any introductory text before the first identified heading of the chunk.** Start directly with the first Markdown-formatted heading. "
    "    *   **Use the provided 'OVERALL HEADINGS CONTEXT' to guide consistent heading levels across chunks.** If a heading appears as Level 1 in the overall context, it should be `#` in the output. If Level 2, `##`, etc. "
    "8.  **Aggressive Redundancy Reduction:** Identify and **AGRESSIVELY remove redundant words, phrases, or sentences** if the meaning remains unchanged. Synthesize closely related sentences into one, but only if they convey the exact same information. **DO NOT repeat information, even if slightly rephrased.** "
    "9.  **Clarify Unclear Sentences:** If a sentence is unclear in the original text, rewrite it clearly *WITHOUT adding any new meaning or making assumptions*. "
    "10. **Output Format:** The output should have the *same logical structure, same topics, and same order* as the input CHUNK TEXT, but with *shorter, clearer sentences*, *simpler vocabulary*, and **correct Markdown headings for TOC generation**. "
    "11. **No Prompt in Output:** DO NOT include any part of this prompt in your output. ONLY provide the rewritten chunk content.\n"
    "12. **No YAML or Horizontal Rules:** CRITICAL: DO NOT generate any YAML front matter (e.g., lines starting and ending with '---') or any content that could be misinterpreted as YAML metadata. **ABSOLUTELY AVOID using '---' or '***' or '___' as horizontal rule separators within the notes.**\n\n"
    "OVERALL HEADINGS CONTEXT:\n{overall_headings_context}\n\n"
    "CHUNK TEXT:\n{chunk}\n"
)

PROMPT_NORMALIZE_TOPIC = (
    "You are a precise topic normalization engine. Your task is to extract a 'canonical_topic_name' "
    "and a list of 'alternative_names' for the provided 'RAW TOPIC NAME' based on the 'CONSOLIDATED TEXT'.\n"
    "**CRITICAL RULES:**\n"
    "1. **NO CREATIVITY:** Use only terms found in or directly implied by the text.\n"
    "2. **NO EXPLANATIONS:** Do not explain the topic.\n"
    "3. **NO REWRITING:** Do not rewrite the content.\n"
    "4. **STRICT JSON:** Output ONLY a JSON object with the keys 'canonical_topic_name' (string) and 'alternative_names' (list of strings).\n"
    "5. **CANONICAL NAME:** The most formal, academic, or widely recognized name for the topic.\n"
    "6. **ALTERNATIVE NAMES:** Other ways the topic is referred to in the text (synonyms, acronyms, etc.).\n\n"
    "RAW TOPIC NAME: {raw_topic_name}\n"
    "CONSOLIDATED TEXT: {consolidated_text}\n"
)

PROMPT_DEDUPLICATE_TOPICS = (
    "You are a semantic deduplication engine. Your task is to identify topics that refer to the same "
    "underlying concept and group them together. For each group, you must decide on a 'primary' name "
    "and list the others as 'secondary' names.\n"
    "**CRITICAL RULES:**\n"
    "1. **SEMANTIC SIMILARITY:** Group topics based on meaning, not just string matching.\n"
    "2. **NO CONTENT REWRITING:** Do not change or summarize any content.\n"
    "3. **STRICT JSON:** Output ONLY a JSON object with a 'merge_groups' key containing a list of objects. "
    "Each object must have 'primary' (string) and 'secondary' (list of strings).\n"
    "4. **PRIMARY SELECTION:** Choose the most formal or comprehensive name as the primary name.\n"
    "5. **ONLY MERGE GROUPS:** Only include topics that actually need merging. If a topic is unique, do not include it in the output.\n\n"
    "TOPICS LIST:\n{topics_list}\n"
)

PROMPT_CLASSIFY_TOPIC = (
    "You are an exam-oriented topic classification engine. Your task is to analyze the provided "
    "'TOPIC NAME' and its 'CONSOLIDATED TEXT' to determine its importance and required explanation depth.\n"
    "**CRITICAL RULES:**\n"
    "1. **NO EXPLANATIONS:** Do not explain the topic.\n"
    "2. **NO REWRITING:** Do not rewrite the content.\n"
    "3. **EXAM LOGIC:** Prioritize core concepts, theories, and processes that are essential for exams.\n"
    "4. **STRICT JSON:** Output ONLY a JSON object with the following keys:\n"
    "   - 'topic_type': One of 'core_concept', 'sub_concept', 'definition_only', 'example', 'application', 'reference_only'.\n"
    "   - 'explanation_depth': One of 'detailed', 'brief', 'none'.\n"
    "   - 'definition_status': One of 'needs_explanation', 'already_explained', 'reference_only'.\n\n"
    "TOPIC NAME: {topic_name}\n"
    "FREQUENCY COUNT: {frequency_count}\n"
    "CONSOLIDATED TEXT: {consolidated_text}\n"
)

PROMPT_MAP_TOPIC_RELATIONSHIPS = (
    "You are a knowledge graph architect. Your task is to identify semantic relationships between a "
    "target 'TOPIC NAME' and a 'LIST OF OTHER TOPICS'.\n"
    "**CRITICAL RULES:**\n"
    "1. **NO REWRITING:** Do not change or summarize any content.\n"
    "2. **NO CIRCULARITY:** Ensure relationships are directional and logical.\n"
    "3. **STRICT JSON:** Output ONLY a JSON object with a 'relationships' key containing a list of objects.\n"
    "4. **RELATION TYPES:** Use ONLY the following relation types:\n"
    "   - 'depends_on': Target topic requires understanding of the other topic.\n"
    "   - 'explains': Target topic provides a definition or explanation for the other topic.\n"
    "   - 'applies': Target topic is a principle or theory applied in the context of the other topic.\n"
    "   - 'exception_to': Target topic is an exception to the rule or theory defined by the other topic.\n"
    "   - 'example_of': Target topic is a specific instance or illustration of the other topic.\n\n"
    "TOPIC NAME: {topic_name}\n"
    "LIST OF OTHER TOPICS: {list_of_other_topics}\n"
)

PROMPT_ACADEMIC_NOTE_WRITER = (
    "You are a professional content writer and academic expert. Your task is to write structured content for the topic '{topic_name}' based on the provided 'NODE CONTENT' and 'RENDERER PROFILE'.\n\n"
    "**RENDERER PROFILE (STRICT ADHERENCE REQUIRED):**\n"
    "- **Profile Name:** {profile_name}\n"
    "- **Bullet Ratio:** {bullet_ratio}\n"
    "- **Prose Ratio:** {prose_ratio}\n"
    "- **Example Handling:** {example_handling}\n"
    "- **Content Freedom:** {content_freedom}\n\n"
    "**INPUT CONTEXT:**\n"
    "- **Explanation Depth:** {explanation_depth}\n"
    "- **Topic Relationships:** {topic_relationships}\n"
    "- **Already Explained Topics:** {already_explained_topics}\n"
    "- **Reference-Only Terms (DO NOT EXPLAIN):** {reference_only_context}\n\n"
    "**CRITICAL RULES:**\n"
    "1. **NO REPETITION:** If a concept is in 'Already Explained Topics', DO NOT explain it again. Instead, **cross-reference** it.\n"
    "2. **CLOSED SET HIERARCHY (MANDATORY):** You MUST adhere to the fixed structural slots. You are NOT allowed to create new subtopics, split topics into new headings, or rename the topic.\n"
    "    - **MERGE**: If '{topic_name}' is semantically identical to a concept in 'Already Explained Topics', signal a merge and provide a brief cross-reference instead of a full explanation.\n"
    "    **FORBIDDEN:**\n"
    "    - Creating additional topics or structural slots.\n"
    "    - Splitting the topic into multiple sub-headings.\n"
    "    - **GENERATING HEADINGS**: You MUST NOT use Markdown headings (e.g., #, ##, ###). Headings are handled by the system.\n"
    "    - Renaming the topic title.\n"
    "    - Recursive subtopic generation.\n"
    "    - Topic inference from passing references.\n"
    "3. **STRICT EXPLANATION LIMITS (MANDATORY):**\n"
    "    - **REFERENCED_ONLY**: If a topic is marked as 'referenced_only', you may MENTION IT ONCE as context. You must NEVER explain or define it.\n"
    "    - **DEPTH LIMITS**: You must NOT exceed the recorded explanation depth provided in 'Explanation Depth'. If a field is 'Forbidden', do not include it.\n"
    "4. **STRICT REFERENCE HANDLING (MANDATORY):** If a term is listed in 'Reference-Only Terms':\n"
    "    - It must NOT be explained or defined.\n"
    "    - It must NOT receive examples.\n"
    "    - It must NOT be expanded into subtopics.\n"
    "    - You may ONLY mention it once as context if it appears in the 'NODE CONTENT'.\n"
    "    - DO NOT use external knowledge to expand on these terms.\n"
    "5. **EXPLANATION DEPTH:** Strictly follow the '{explanation_depth}' requirement.\n"
    "3. **FORMATTING (PROFILE-BASED):**\n"
    "   - If Bullet Ratio is 'high' or 'very_high', use extensive bullet points and lists.\n"
    "   - If Prose Ratio is 'high', use flowing paragraphs and narrative structure.\n"
    "4. **CONTENT FREEDOM (STRICT ENFORCEMENT):**\n"
    "   - If 'allow_enhancement': You are encouraged to improve explanations, add missing clarity, and replace weak text with stronger academic prose. You MUST stay concept-aligned with the 'NODE CONTENT' but can use external pedagogical techniques to enhance understanding.\n"
    "   - If 'restricted': Stick closely to the source. Allow minor rephrasing for clarity and flow, but do not add new concepts or analogies.\n"
    "   - If 'forbidden': You MUST use ONLY the information present in the 'NODE CONTENT'. DO NOT introduce new ideas, DO NOT add external knowledge, and DO NOT make inferences beyond what is explicitly stated. Any violation of this rule will result in the output being rejected.\n"
    "5. **EXAMPLE HANDLING (TAG-AWARE):**\n"
    "   - If 'keep_all', include all provided 'TAGGED EXAMPLES'.\n"
    "   - If 'compress_or_drop_low_relevance', drop 'low' relevance examples and shorten 'compressible' ones.\n"
    "   - ALWAYS preserve core facts and outcomes, bolding key identifiers.\n"
    "6. **OUTPUT FORMAT (STRICT):**\n"
    "   Your output MUST start with a JSON block containing any FLEX actions taken, followed by the Markdown content.\n"
    "   Example:\n"
    "   ```json\n"
    "   {{\n"
    "     \"flex_actions\": [\n"
    "       {{\"action\": \"RENAME\", \"original\": \"...\", \"new\": \"...\", \"reason\": \"...\"}},\n"
    "       {{\"action\": \"MERGE\", \"with\": \"...\", \"reason\": \"...\"}},\n"
    "       {{\"action\": \"SPLIT\", \"concepts\": [\"...\", \"...\"], \"reason\": \"...\"}}\n"
    "     ]\n"
    "   }}\n"
    "   ```\n"
    "   If no flex actions are taken, provide an empty list: `\"flex_actions\": []`.\n"
    "   Follow the JSON block with the Markdown content.\n\n"
    "**STRICT GUARD CLAUSE:**\n"
    "{guard_clause}\n\n"
    "NODE CONTENT:\n{node_content}\n\n"
    "TAGGED EXAMPLES:\n{tagged_examples}\n"
)

PROMPT_VERIFY_OUTPUT = (
    "You are an expert Quality Assurance Verifier. Your task is to perform HARD INVARIANCE CHECKS on the 'GENERATED OUTPUT' against the 'KNOWLEDGE BLUEPRINT'.\n\n"
    "**HARD INVARIANCE CHECKS (MANDATORY):**\n"
    "1. **TOPIC COUNT:** Does the number of rendered topics exactly match the number of topics in the blueprint?\n"
    "2. **HIERARCHY DEPTH:** Is the hierarchy depth identical to the blueprint? (No new levels allowed).\n"
    "3. **NO NEW HEADINGS:** Are there any headings in the output that are NOT present in the blueprint?\n"
    "4. **REFERENCED_ONLY ENFORCEMENT:** Are any topics marked as 'referenced_only' explained or defined? (They must only be mentioned once as context).\n"
    "5. **DEPTH ENFORCEMENT:** Did the renderer exceed the recorded explanation depth for any topic?\n\n"
    "**OUTPUT FORMAT:**\n"
    "Output ONLY a JSON object with the following keys:\n"
    "- valid: true/false (Set to false if ANY invariance check fails).\n"
    "- reason: A detailed explanation of the failure.\n"
    "- violations: A list of specific violation types found (e.g., 'TOPIC_COUNT_MISMATCH', 'DEPTH_INCREASED', 'NEW_HEADING', 'REFERENCE_EXPLAINED', 'DEPTH_EXCEEDED').\n"
    "- stats: A JSON object with:\n"
    "    - blueprint_topic_count: int\n"
    "    - rendered_topic_count: int\n"
    "    - blueprint_depth: int\n"
    "    - rendered_depth: int\n"
    "- confidence: A float between 0.0 and 1.0 representing your confidence in this verification.\n\n"
    "**STRICT JSON:** Output ONLY the JSON object. No conversational text or markdown fences.\n\n"
    "KNOWLEDGE BLUEPRINT:\n{blueprint_context}\n\n"
    "RENDERER PROFILE:\n{profile_context}\n\n"
    "GENERATED OUTPUT:\n{generated_output}\n"
)

PROMPT_MAP_QUESTION_TO_CONCEPTS = (
    "You are a Knowledge Mapping Agent. Your task is to analyze the 'USER QUESTION' and identify which concepts from the 'KNOWLEDGE BLUEPRINT' are required to answer it accurately.\n\n"
    "**CRITICAL RULES:**\n"
    "1. **STRICT MAPPING:** Only map to concepts explicitly present in the blueprint using their 'concept_id'.\n"
    "2. **CONFIDENCE SCORING:** Assign a confidence score (0.0 to 1.0) based on how well the blueprint covers the question.\n"
    "3. **NO EXTERNAL KNOWLEDGE:** Do not assume concepts not in the blueprint.\n\n"
    "**OUTPUT FORMAT:**\n"
    "Output ONLY a JSON object with:\n"
    "- mapped_concept_ids: A list of concept IDs.\n"
    "- confidence: A float (0.0 to 1.0).\n"
    "- gap_analysis: A brief explanation if the blueprint is insufficient.\n\n"
    "**STRICT JSON:** Output ONLY the JSON object.\n\n"
    "KNOWLEDGE BLUEPRINT CONCEPTS:\n{blueprint_concepts}\n\n"
    "USER QUESTION:\n{user_question}\n"
)

PROMPT_DETECT_CONTRADICTION = (
    "You are a Fact-Checking Agent. Your task is to compare two academic explanations for the same concept and determine if they conflict in meaning or factual correctness.\n\n"
    "**CRITICAL RULES:**\n"
    "1. **CONFLICT DETECTION:** Identify if the two texts provide contradictory facts, definitions, or processes.\n"
    "2. **RESOLUTION LOGIC:** If a conflict exists, select the 'preferred' explanation based on clarity, academic formulation, and completeness.\n"
    "3. **NO MERGING:** Do not merge the texts. Select one as the primary and mark the other as rejected.\n\n"
    "**OUTPUT FORMAT:**\n"
    "Output ONLY a JSON object with:\n"
    "- conflict: true/false\n"
    "- preferred_index: 1 or 2 (the index of the better explanation)\n"
    "- reason: A brief explanation of the conflict and why the preferred one was chosen.\n\n"
    "**STRICT JSON:** Output ONLY the JSON object.\n\n"
    "EXPLANATION 1:\n{text1}\n\n"
    "EXPLANATION 2:\n{text2}\n"
)

PROMPT_DETECT_CONCEPT_DRIFT = (
    "You are a Semantic Analysis Agent. Your task is to compare an 'EARLY EXPLANATION' and a 'LATE EXPLANATION' of the same concept from different parts of a book and determine if the emphasis or meaning has drifted significantly.\n\n"
    "**CRITICAL RULES:**\n"
    "1. **DRIFT DETECTION:** Identify if the late explanation introduces significant new nuances, changes the core definition, or shifts the pedagogical focus compared to the early one.\n"
    "2. **INFORMATIONAL ONLY:** This is for warning purposes. Do not attempt to resolve or merge.\n\n"
    "**OUTPUT FORMAT:**\n"
    "Output ONLY a JSON object with:\n"
    "- drift_warning: true/false\n"
    "- drift_reason: A brief explanation of how the emphasis or meaning has shifted (if true).\n\n"
    "**STRICT JSON:** Output ONLY the JSON object.\n\n"
    "EARLY EXPLANATION:\n{early_text}\n\n"
    "LATE EXPLANATION:\n{late_text}\n"
)

PROMPT_COMPRESS_EXAMPLE = (
    "You are a Precise Compression Agent. Your task is to shorten the provided 'ACADEMIC EXAMPLE' while preserving its core logic.\n\n"
    "**COMPRESSION RULES:**\n"
    "1. **PRESERVE PREMISE:** Keep the initial problem, scenario, or setup.\n"
    "2. **PRESERVE OUTCOME:** Keep the final conclusion, result, or takeaway.\n"
    "3. **REMOVE NARRATIVE:** Strip away story-like wording, character names (unless essential), and descriptive filler.\n"
    "4. **REMOVE REDUNDANCY:** Delete any repeated explanations or meta-commentary.\n"
    "5. **NO NEW CONTENT:** Do not add any information not present in the original. You may only rephrase for conciseness.\n\n"
    "**OUTPUT FORMAT:**\n"
    "Return ONLY the compressed text. No intros or outros.\n\n"
    "ACADEMIC EXAMPLE:\n{example_text}\n"
)

PROMPT_ANALYZE_CONTENT_DEPTH = (
    "You are an expert Academic Content Analyst. Your task is to analyze the provided 'CONTENT' "
    "in the context of the structural node '{node_path}' and determine its usage type, explanation depth, and source extent.\n\n"
    "**ANALYSIS CRITERIA:**\n"
    "1. **usage_type**:\n"
    "   - 'explained': The content provides a clear definition or detailed explanation of the topic.\n"
    "   - 'contextual': The topic is mentioned with some context but not fully explained.\n"
    "   - 'referenced_only': The topic is only mentioned in passing or as a reference.\n"
    "2. **explanation_depth**:\n"
    "   - definition: Does it provide a formal definition? (true/false)\n"
    "   - intuition: Does it provide conceptual intuition or analogies? (true/false)\n"
    "   - derivation: Does it show how a formula or principle is derived? (true/false)\n"
    "   - examples: What is the level of examples provided? (none | brief | full)\n"
    "   - proof: Does it include a formal proof or theorem verification? (true/false)\n"
    "3. **max_source_extent**:\n"
    "   - Estimate the volume of source material dedicated to this topic (e.g., '2 paragraphs', '1.5 pages', '5 sentences').\n\n"
    "**CRITICAL RULES:**\n"
    "- If the content is empty or irrelevant, set usage_type to 'referenced_only'.\n"
    "- Base your analysis ONLY on the provided 'CONTENT'.\n"
    "- Output ONLY a JSON object.\n\n"
    "**OUTPUT FORMAT:**\n"
    "```json\n"
    "{{\n"
    "  \"usage_type\": \"...\",\n"
    "  \"explanation_depth\": {{\n"
    "    \"definition\": true/false,\n"
    "    \"intuition\": true/false,\n"
    "    \"derivation\": true/false,\n"
    "    \"examples\": \"none/brief/full\",\n"
    "    \"proof\": true/false\n"
    "  }},\n"
    "  \"max_source_extent\": \"...\"\n"
    "}}\n"
    "```\n\n"
    "NODE PATH: {node_path}\n"
    "CONTENT:\n{content}\n"
)

PROMPT_MAP_CONCEPTS_TO_STRUCTURE = (
    "You are an expert in content organization. Your task is to map a list of 'DISCOVERED CONCEPTS' to a 'BOOK STRUCTURE'.\n"
    "For each node in the 'BOOK STRUCTURE', identify which concepts from the 'DISCOVERED CONCEPTS' belong to it based on semantic relevance and hierarchy.\n\n"
    "**CRITICAL RULES:**\n"
    "1. A concept can belong to multiple nodes if relevant.\n"
    "2. A node can have multiple concepts.\n"
    "3. Use the exact 'concept_id' provided.\n"
    "4. If a concept doesn't fit anywhere, do not map it.\n"
    "5. If a node has no relevant concepts, leave its 'concept_ids' empty.\n"
    "6. **STRICT JSON:** Output ONLY the JSON object. No conversational text or markdown fences.\n\n"
    "**OUTPUT FORMAT:**\n"
    "Return a JSON object where keys are the 'original_structure_path' and values are lists of 'concept_id's.\n"
    "Example:\n"
    "{{\n"
    "  \"Chapter 1 > Section 1.1\": [\"id1\", \"id2\"],\n"
    "  \"Chapter 1 > Section 1.2\": [\"id3\"]\n"
    "}}\n\n"
    "BOOK STRUCTURE PATHS:\n{structure_paths}\n\n"
    "DISCOVERED CONCEPTS:\n{concepts_summary}\n"
)

PROMPT_GENERATE_DERIVED_BLUEPRINT = (
    "You are an expert Content Architect. Your task is to transform a 'SOURCE BLUEPRINT' into a 'DERIVED BLUEPRINT' "
    "optimized for user-facing notes, while strictly adhering to architectural constraints.\n\n"
    "**STRUCTURAL FLEXIBILITY RULES:**\n"
    "You are allowed specific structural flexibility to improve the user experience:\n"
    "1. **Rename Topic Titles**: You may rename titles for better clarity or simplification.\n"
    "2. **Merge Topics**: You may merge multiple SourceBlueprint topics into a single node.\n"
    "3. **Reorder Topics**: You may reorder topics WITHIN THE SAME CHAPTER to improve logical flow.\n\n"
    "**STRICT PROHIBITIONS (NON-NEGOTIABLE):**\n"
    "1. **NO NEW TOPICS**: You cannot introduce topics not present in the Source Blueprint.\n"
    "2. **NO NEW LEVELS**: You cannot increase hierarchy depth (e.g., no new sub-sub-sections).\n"
    "3. **NO REMOVING CHAPTERS**: All chapters from the Source Blueprint must be preserved.\n"
    "4. **MAPPING INTEGRITY**: Every node in your output MUST map to at least one 'concept_id' from the Source Blueprint.\n\n"
    "**OUTPUT FORMAT:**\n"
    "Output a JSON object representing the new hierarchy. Each node must include:\n"
    "- title: The new (or original) title.\n"
    "- concept_ids: A list of concept IDs from the Source Blueprint that this node represents.\n"
    "- allowed_expansion: One of 'rephrase_only', 'enhance', or 'compress'.\n"
    "- children: (Optional) Sub-nodes.\n\n"
    "**SOURCE BLUEPRINT HIERARCHY:**\n"
    "{source_hierarchy}\n\n"
    "**AUTHORIAL INTENT:**\n"
    "{authorial_intent}\n"
)
