# Common prompt templates for various LLM operations

# PROMPT for Chunk-by-Chunk Simplified Rewriting
PROMPT_EXTRACT_BOOK_STRUCTURE = (
    "You are an expert in analyzing book structures. Your task is to extract the hierarchical structure "
    "of the provided 'FULL BOOK TEXT'. This includes chapter titles, section headings, and subheadings, "
    "preserving their exact order and hierarchy. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **Output ONLY the JSON array.** DO NOT include any conversational text, markdown code block fences (```json), or any other characters before or after the JSON. "
    "2.  **DO NOT extract any explanations or content summaries.** ONLY extract the structure. "
    "3.  **DO NOT summarize content.** "
    "4.  **Output must be STRUCTURE ONLY.** "
    "5.  **Represent the structure as a JSON array of objects.** Each object should have a 'title' and an optional 'children' array for subheadings. "
    "6.  **Infer hierarchy based on formatting, numbering, and context.** "
    "7.  **Example Output Format (STRICTLY ADHERE TO THIS):**\n"
    "    ```json\n"
    "    [\n"
    "        {{\n"
    "            \"title\": \"Chapter 1: Introduction to Law\",\n"
    "            \"children\": [\n"
    "                {{\"title\": \"Meaning of Law\"}},\n"
    "                {{\"title\": \"Sources of Law\"}},\n"
    "                {{\n"
    "                    \"title\": \"Types of Law\",\n"
    "                    \"children\": [\n"
    "                        {{\"title\": \"Public Law\"}},\n"
    "                        {{\"title\": \"Private Law\"}}\n"
    "                    ]\n"
    "                }}\n"
    "            ]\n"
    "        }},\n"
    "        {{\n"
    "            \"title\": \"Chapter 2: Contracts\",\n"
    "            \"children\": [\n"
    "                {{\"title\": \"Elements of a Contract\"}},\n"
    "                {{\"title\": \"Offer and Acceptance\"}}\n"
    "            ]\n"
    "        }}\n"
    "    ]\n"
    "    ```\n\n"
    "FULL BOOK TEXT:\n{full_text}\n"
)

PROMPT_MAP_CHUNK_TO_STRUCTURE = (
    "You are an expert in content organization and precise text extraction. Your task is to analyze the "
    "'CHUNK TEXT' and identify which of the provided 'BOOK STRUCTURE TITLES' it is relevant to. "
    "For each relevant title, you must extract *only* the sentences or paragraphs from the 'CHUNK TEXT' "
    "that directly explain or mention that specific topic. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **Output a JSON array of objects.** Each object must have two keys: "
    "    *   `title`: The exact title of the structure node (string). "
    "    *   `source_text`: A string containing *only* the relevant sentences/paragraphs from the 'CHUNK TEXT' "
    "        that directly pertain to this `title`. If multiple parts of the chunk are relevant, merge them. "
    "2.  **Output ONLY the JSON array.** DO NOT include any conversational text, markdown code block fences (```json), or any other characters before or after the JSON. "
    "3.  **Match the `title` exactly as provided in 'BOOK STRUCTURE TITLES'.** "
    "4.  **Consider the full hierarchical path** (e.g., 'Chapter 1 > Section A > Subheading 1') when mapping. "
    "5.  **DO NOT rewrite, summarize, or generate explanations.** ONLY extract and attach raw PDF text. "
    "6.  **DO NOT add any new information.** The `source_text` must be verbatim from the 'CHUNK TEXT'. "
    "7.  **If a chunk contains content relevant to multiple nodes, create a separate object for each relevant node.** "
    "8.  **If a chunk does not clearly map to any specific node, return an empty JSON array `[]`.**\n"
    "9.  **Example Output Format (STRICTLY ADHERE TO THIS):**\n"
    "    ```json\n"
    "    [\n"
    "        {{\n"
    "            \"title\": \"Chapter 1: Introduction to Law > Meaning of Law\",\n"
    "            \"source_text\": \"Law is a system of rules that are created and enforced through social or governmental institutions to regulate behavior.\"\n"
    "        }},\n"
    "        {{\n"
    "            \"title\": \"Chapter 1: Introduction to Law > Types of Law > Public Law\",\n"
    "            \"source_text\": \"Public law governs the relationship between individuals and the government, and includes constitutional law, administrative law, and criminal law.\"\n"
    "        }}\n"
    "    ]\n"
    "    ```\n\n"
    "BOOK STRUCTURE TITLES:\n{book_structure_titles}\n\n"
    "CHUNK TEXT:\n{chunk_text}\n"
)

PROMPT_CONSOLIDATE_CONCEPTS = (
    "You are an expert in synthesizing information and removing redundancy. "
    "Your task is to consolidate the provided 'RAW NODE CONTENT' for a specific book structure node. "
    "Identify and combine repeated concepts or explanations within *this content only* into one coherent explanation. "
    "Preserve ALL unique information and remove all redundancy. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **DO NOT introduce any information not present in the RAW NODE CONTENT.** "
    "2.  **DO NOT remove any unique information.** "
    "3.  **DO NOT merge content ACROSS different structure nodes.** Focus strictly on the provided 'RAW NODE CONTENT'. "
    "4.  **Output the consolidated text in clear, simple English.** "
    "5.  **Maintain the original academic/legal meaning.** "
    "6.  **Aggressively remove redundant words, phrases, or sentences.** Synthesize closely related sentences into one if they convey the exact same information. "
    "7.  **The output should be a single, coherent block of text** that represents all unique information from the raw content without repetition.\n\n"
    "RAW NODE CONTENT:\n{raw_node_content}\n"
)

PROMPT_REWRITE_NODE_CONTROLLED = (
    "You are an expert in simplifying complex legal texts for exam preparation, focusing on conceptual depth and clarity for a first-time reader. "
    "Your task is to rewrite the provided 'NODE CONTENT' for the topic '{node_title}' into detailed, clear, and exam-ready notes.\n"
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **SOURCE GUIDANCE & EXPANSION (MANDATORY):** Prioritize the provided 'NODE CONTENT'. If a point lacks sufficient detail to be self-explanatory or is too concise, you MUST expand on it by 15-20% and add relevant, concise examples to enhance clarity. These additions MUST be logical extensions of the existing content and NOT introduce new, unrelated concepts. Ensure the output is always more detailed than the input if the input is brief.\n"
    "2.  **DEPTH RULE (MANDATORY):** When rewriting, preserve ALL conceptual explanations, ALL examples, ALL case laws/illustrations, ALL exceptions and conditions, and ALL reasoning steps. You may simplify language, but NEVER simplify or remove ideas.\n"
    "3.  **CONCEPT USAGE vs. DEFINITION (CRITICAL):**\n"
    "    *   **Concept Definition Section:** If the 'NODE CONTENT' explicitly defines or elaborates on a concept (meaning, scope, elements, rationale, case law), provide a FULL explanation. Assume the reader is a complete beginner with no prior legal background.\n"
    "    *   **Concept Usage:** If a concept is merely used or referenced (e.g., 'This principle applies subject to Volenti non-fit Injuria'), DO NOT explain it here. Keep its usage brief and contextual.\n"
    "4.  **PRIMARY EXPLANATION vs. REFERENCE:** If this topic is the main place where a concept is explained, explain it in FULL. If another topic refers to it, only provide a brief contextual mention.\n"
    "5.  **DEDUPLICATION:** DO NOT repeat explanations. If a concept is listed in 'Concepts Already Explained', assume it has been covered and DO NOT explain it again. Only reference it if necessary.\n"
    "6.  **EXPLANATION STYLE (VERY IMPORTANT):** Rewrite content so a first-time reader can understand. Each concept should implicitly answer: What it is, Why it exists, How it applies, and What happens if violated. Use short paragraphs, clear bullet points (`- `), numbered lists (`1. `), simple English, and a logical flow. Ensure consistent indentation for lists.\n"
    "7.  **EXAMPLES & CASE LAWS (DO NOT SHORTEN):** If examples or case laws exist in the 'NODE CONTENT', keep ALL of them. Explain facts, issue, and outcome in simple words. DO NOT compress them to one line or remove reasoning. Case laws are learning tools, not just references.\n"
    "8.  **LENGTH CONTROL (IMPORTANT):** You MUST condense content by rewriting sentences in simpler English, breaking long sentences into clearer shorter sentences, or explaining existing ideas using different words already implied in the text. You MUST NOT add new concepts, examples, reasoning, or interpretations. Target output: 50-60% of original informational content, focusing on conciseness for a first-time learner. Ensure this reduction is always applied.\n"
    "9.  **ABSOLUTE PROHIBITIONS:**\n"
    "    *   ❌ No over-summarization.\n"
    "    *   ❌ No 'In short', 'Briefly', 'Simply put' replacements.\n"
    "    *   ❌ No conceptual shortcuts.\n"
    "    *   ❌ No skipping explanation because it was 'already mentioned' if this is the primary definition section.\n"
    "    *   ❌ DO NOT add generic introductions or conclusions. Start directly with the rewritten content.\n"
    "10. **Output Format (STRICTLY ENFORCED):** Provide only the rewritten text. DO NOT include any Markdown headings here; they will be added by the system. Ensure all lists (bulleted or numbered) are correctly formatted with a space after the marker (e.g., `- Item` or `1. Item`). **CRITICAL: For bullet points and numbered lists, ensure each item starts on a new line. Each bullet point or numbered list item MUST be on its own line. Ensure there is a blank line (`\\n\\n`) before the start of any list. If a bullet point or numbered list item is generated, it must be on its own line, and not immediately follow other text on the same line. Use a single newline (`\\n`) to separate paragraphs within a bullet point or list item, but ensure a blank line (`\\n\\n`) separates distinct bullet points or numbered list items from each other and from surrounding paragraphs. Also, ensure that if a bullet point or numbered list item contains multiple sentences, they are all part of the same list item and not broken into separate list items or paragraphs. Each distinct point in a list must be a separate bullet or numbered item. DO NOT allow any text to appear on the same line as a bullet point or numbered list marker, other than the content of that specific list item. If a list item contains sub-points, these should be indented and formatted as sub-lists.**\n"
    "11. **Concepts Already Explained (for reference, do not re-explain these):**\n{explained_concepts_context}\n\n"
    "NODE CONTENT:\n{node_content}\n"
)

PROMPT_REWRITE_CHUNK_SIMPLIFIED = (
    "You are an expert in simplifying complex legal texts for exam preparation. "
    "Your task is to rewrite the provided 'CHUNK TEXT' in *simpler, direct English*, making it *significantly shorter* (aim for 50% reduction), "
    "while strictly preserving the original meaning, structure, and order. "
    "**CRITICAL RULES (NON-NEGOTIABLE):**\n"
    "1.  **DO NOT introduce any information that is not explicitly present in the CHUNK TEXT.** This includes explanations, background knowledge, interpretations, or legal reasoning not directly stated. "
    "2.  **DO NOT add examples unless they are explicitly present in the CHUNK TEXT.** If an example is in the text, simplify it. "
    "3.  **DO NOT combine information from different sections or chunks.** Process each chunk in isolation. "
    "4.  **DO NOT reorder topics or headings globally.** Maintain the original sequence of information as it appears in the CHUNK TEXT. "
    "5.  **DO NOT 'explain' concepts beyond simplifying their wording.** Focus on replacing complex sentences and difficult words with easier equivalents. "
    "6.  **DO NOT summarize across chunks.** Rewrite the content of *this specific chunk only*. "
    "7.  **Strict Heading Identification & Markdown Formatting (ABSOLUTE PRIORITY):** "
    "    *   **Identify headings and subheadings based on their visual cues in the original CHUNK TEXT** (e.g., bold text, distinct lines, numbering/lettering). "
    "    *   **Extract only the *semantic content* of the original heading.** Discard any original numbering or lettering (e.g., '1.1', 'A.', 'I.'). "
    "    *   **Apply the appropriate Markdown heading syntax (`#`, `##`, `###`)** based on the *inferred hierarchy* of the semantic content. "
    "        *   Use `#` (H1) for the main topic of the chunk. "
    "        *   Use `##` (H2) for major sub-sections. "
    "        *   Use `###` (H3) for minor sub-sections. "
    "    *   **CRITICAL: DO NOT create any NEW headings or subheadings that are not clearly present in the original CHUNK TEXT.** "
    "    *   **CRITICAL: All identified headings MUST be converted to Markdown headings for TOC generation.** "
    "    *   **DO NOT include any introductory text before the first identified heading of the chunk.** Start directly with the first Markdown-formatted heading. "
    "    *   **Use the provided 'OVERALL HEADINGS CONTEXT' to guide consistent heading levels across chunks.** If a heading appears as Level 1 in the overall context, it should be `#` in the output. If Level 2, `##`, etc. "
    "8.  **Aggressive Redundancy Reduction:** Identify and **AGRESSIVELY remove redundant words, phrases, or sentences** if the meaning remains unchanged. Synthesize closely related sentences into one, but only if they convey the exact same information. **DO NOT repeat information, even if slightly rephrased.** "
    "9.  **Clarify Unclear Sentences:** If a sentence is unclear in the original text, rewrite it clearly *WITHOUT adding any new meaning or making assumptions*. "
    "10. **Output Format:** The output should have the *same logical structure, same topics, and same order* as the input CHUNK TEXT, but with *shorter, clearer sentences*, *simpler vocabulary*, and **correct Markdown headings for TOC generation**. "
    "11. **No Prompt in Output:** DO NOT include any part of this prompt in your output. ONLY provide the rewritten chunk content.\n"
    "12. **No YAML or Horizontal Rules:** CRITICAL: DO NOT generate any YAML front matter (e.g., lines starting and ending with '---') or any content that could be misinterpreted as YAML metadata. **ABSOLUTELY AVOID using '---' or '***' or '___' as horizontal rule separators within the notes.**\n\n"
    "OVERALL HEADINGS CONTEXT:\n{overall_headings_context}\n\n"
    "CHUNK TEXT:\n{chunk}\n"
)
